import { DARK_STYLE, LIGHT_STYLE } from '@constants/style';

const GLOBAL_LIGHT_STYLE_KEY = 'GLOBAL_LIGHT_STYLE_KEY';

const GLOBAL_DARK_STYLE_KEY = 'GLOBAL_DARK_STYLE_KEY';

const GLOBAL_STYLE_RULE_KEY = 'GLOBAL_STYLE_RULE_KEY';

const GLOBAL_DARKMODE_STATE = 'GLOBAL_DARKMODE_STATE';

const INITIAL_STATES = {
  [GLOBAL_LIGHT_STYLE_KEY]: LIGHT_STYLE,
  [GLOBAL_DARK_STYLE_KEY]: DARK_STYLE,
  [GLOBAL_STYLE_RULE_KEY]: {},
  [GLOBAL_DARKMODE_STATE]: false,
};

export { GLOBAL_DARK_STYLE_KEY, GLOBAL_DARKMODE_STATE, GLOBAL_LIGHT_STYLE_KEY, GLOBAL_STYLE_RULE_KEY, INITIAL_STATES };
