import { LIB_DEFAULT } from '@constants/default';

export const PositionBuilder = (style: IAppStyles) => ({
  top: (offset: number | string = 0) => ({
    top: offset,
  }),
  top0: { top: 0 },
  top1: { top: style.SOLID.l1 },
  top2: { top: style.SOLID.l4 },
  left: (offset: number | string = 0) => ({
    left: offset,
  }),
  left0: { left: 0 },
  left1: { left: style.SOLID.l1 },
  left2: { left: style.SOLID.l4 },
  right: (offset: number | string = 0) => ({
    right: offset,
  }),
  right0: { right: 0 },
  right1: { right: style.SOLID.l1 },
  right2: { right: style.SOLID.l4 },
  bottom: (offset: number | string = 0) => ({
    bottom: offset,
  }),
  bottom0: { bottom: 0 },
  bottom1: { bottom: style.SOLID.l1 },
  bottom2: { bottom: style.SOLID.l4 },
  z: (index = 1) => ({
    zIndex: index,
  }),
  z0: { zIndex: 0 },
  z1: { zIndex: style.SOLID.l1 },
  z2: { zIndex: style.SOLID.l2 },
  z3: { zIndex: style.SOLID.l3 },
  z100: { zIndex: 100 },
  z999: { zIndex: 999 },
  z9999: { zIndex: 9999 },
  pa: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    padding: size,
  }),
  pa0: { padding: 0 },
  pa1: { padding: style.SOLID.l1 },
  pa2: { padding: style.SOLID.l2 },
  pa3: { padding: style.SOLID.l3 },
  pa4: { padding: style.SOLID.l4 },
  pa5: { padding: style.SOLID.l5 },
  pa6: { padding: style.SOLID.l6 },
  pa7: { padding: style.SOLID.l7 },
  pt: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    paddingTop: size,
  }),
  pt0: { paddingTop: 0 },
  pt1: { paddingTop: style.SOLID.l1 },
  pt2: { paddingTop: style.SOLID.l2 },
  pt3: { paddingTop: style.SOLID.l3 },
  pt4: { paddingTop: style.SOLID.l4 },
  pt5: { paddingTop: style.SOLID.l5 },
  pt6: { paddingTop: style.SOLID.l6 },
  pt7: { paddingTop: style.SOLID.l7 },
  pr: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    paddingRight: size,
  }),
  pr0: { paddingRight: 0 },
  pr1: { paddingRight: style.SOLID.l1 },
  pr2: { paddingRight: style.SOLID.l2 },
  pr3: { paddingRight: style.SOLID.l3 },
  pr4: { paddingRight: style.SOLID.l4 },
  pr5: { paddingRight: style.SOLID.l5 },
  pr6: { paddingRight: style.SOLID.l6 },
  pr7: { paddingRight: style.SOLID.l7 },
  pb: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    paddingBottom: size,
  }),
  pb0: { paddingBottom: 0 },
  pb1: { paddingBottom: style.SOLID.l1 },
  pb2: { paddingBottom: style.SOLID.l2 },
  pb3: { paddingBottom: style.SOLID.l3 },
  pb4: { paddingBottom: style.SOLID.l4 },
  pb5: { paddingBottom: style.SOLID.l5 },
  pb6: { paddingBottom: style.SOLID.l6 },
  pb7: { paddingBottom: style.SOLID.l7 },
  pl: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    paddingLeft: size,
  }),
  pl0: { paddingLeft: 0 },
  pl1: { paddingLeft: style.SOLID.l1 },
  pl2: { paddingLeft: style.SOLID.l2 },
  pl3: { paddingLeft: style.SOLID.l3 },
  pl4: { paddingLeft: style.SOLID.l4 },
  pl5: { paddingLeft: style.SOLID.l5 },
  pl6: { paddingLeft: style.SOLID.l6 },
  pl7: { paddingLeft: style.SOLID.l7 },
  ma: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    margin: size,
  }),
  ma0: { margin: 0 },
  ma1: { margin: style.SOLID.l1 },
  ma2: { margin: style.SOLID.l2 },
  ma3: { margin: style.SOLID.l3 },
  ma4: { margin: style.SOLID.l4 },
  ma5: { margin: style.SOLID.l5 },
  ma6: { margin: style.SOLID.l6 },
  ma7: { margin: style.SOLID.l7 },
  mt: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    marginTop: size,
  }),
  mt0: { marginTop: 0 },
  mt1: { marginTop: style.SOLID.l1 },
  mt2: { marginTop: style.SOLID.l2 },
  mt3: { marginTop: style.SOLID.l3 },
  mt4: { marginTop: style.SOLID.l4 },
  mt5: { marginTop: style.SOLID.l5 },
  mt6: { marginTop: style.SOLID.l6 },
  mt7: { marginTop: style.SOLID.l7 },
  mr: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    marginRight: size,
  }),
  mr0: { marginRight: 0 },
  mr1: { marginRight: style.SOLID.l1 },
  mr2: { marginRight: style.SOLID.l2 },
  mr3: { marginRight: style.SOLID.l3 },
  mr4: { marginRight: style.SOLID.l4 },
  mr5: { marginRight: style.SOLID.l5 },
  mr6: { marginRight: style.SOLID.l6 },
  mr7: { marginRight: style.SOLID.l7 },
  mb: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    marginBottom: size,
  }),
  mb0: { marginBottom: 0 },
  mb1: { marginBottom: style.SOLID.l1 },
  mb2: { marginBottom: style.SOLID.l2 },
  mb3: { marginBottom: style.SOLID.l3 },
  mb4: { marginBottom: style.SOLID.l4 },
  mb5: { marginBottom: style.SOLID.l5 },
  mb6: { marginBottom: style.SOLID.l6 },
  mb7: { marginBottom: style.SOLID.l7 },
  ml: (size: number | string = LIB_DEFAULT.SOLID_SIZE.l1) => ({
    marginLeft: size,
  }),
  ml0: { marginLeft: 0 },
  ml1: { marginLeft: style.SOLID.l1 },
  ml2: { marginLeft: style.SOLID.l2 },
  ml3: { marginLeft: style.SOLID.l3 },
  ml4: { marginLeft: style.SOLID.l4 },
  ml5: { marginLeft: style.SOLID.l5 },
  ml6: { marginLeft: style.SOLID.l6 },
  ml7: { marginLeft: style.SOLID.l7 },
});

export type TPositionBuilderKey = ReturnType<typeof PositionBuilder>;
